### ISSUE TITLE
Configuration code samples missing

### ISSUE THREAD

**Issue by siddhantg-cbre** [awsdocs/aws-mobile-developer-guide#17]
The code samples for Android in the 'Connect to your backend' section are missing at  
aws-mobile-developer-guide/doc_source/add-aws-mobile-conversational-bots.rst

**Comment by dzucker-amzn** [comment]
@siddhantg-cbre  thanks for your comment. This turns out to be an issue related to using the .rst `emphasize-lines` directive which allows you to see which sample code lines are relevant (vs. shown for context). This line highlighting works when you build the docs using SPhinx (see readme.md). Unfortunately, we discovered recently that when the docs are rendered on Github, it makes the code disappear. Removing the emphasize-lines directives is on our backlog, and I'll move the priority up now that I see it's really getting in folks way.

You can view the code by clicking on the Raw view for each doc or view the doc at: https://docs.aws.amazon.com/aws-mobile/latest/developerguide/add-aws-mobile-conversational-bots.html.

**Comment by dzucker-amzn** [comment]
@Siddhartha-cbre  got this fixed. Please reopen if you find any problems. And thanks again!
